# Generated by Django 3.0.6 on 2020-05-27 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEmployee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identification for an account.', primary_key=True, serialize=False)),
                ('slug', models.CharField(default='onboard', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelRedirectUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info', models.BooleanField(default=False)),
                ('family_info', models.BooleanField(default=False)),
                ('emergency_contact', models.BooleanField(default=False)),
                ('document_gathering', models.BooleanField(default=False)),
                ('drug_declaration', models.BooleanField(default=False)),
                ('bank_detail', models.BooleanField(default=False)),
                ('user', models.IntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.ModelEmployee')),
            ],
            options={
                'verbose_name': 'Redirect Url',
                'verbose_name_plural': 'Redirect Url',
                'db_table': 'redirect_url',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelPersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')])),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('contact', models.IntegerField()),
                ('post_code', models.IntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.ModelEmployee')),
            ],
            options={
                'verbose_name': 'Personal Details',
                'verbose_name_plural': 'Personal Details',
                'db_table': 'personal_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelFamilyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('siblings', models.IntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.ModelEmployee')),
            ],
            options={
                'verbose_name': 'Family Details',
                'verbose_name_plural': 'Family Details',
                'db_table': 'family_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelEmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_contact', models.IntegerField()),
                ('frient_contact', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.ModelEmployee')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contact',
                'db_table': 'emergency_contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelDocumentGathering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee/documents/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.ModelEmployee')),
            ],
            options={
                'verbose_name': 'Documents',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='ModelBankingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('ifsc', models.IntegerField()),
                ('acoount_number', models.IntegerField()),
                ('branch_nme', models.CharField(max_length=255)),
                ('bank_address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('bank_post_code', models.IntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.ModelEmployee')),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Detail',
                'db_table': 'bank_detail',
                'managed': True,
            },
        ),
    ]
