# Generated by Django 3.0.6 on 2020-05-25 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200522_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelemployee',
            name='uid',
        ),
        migrations.AddField(
            model_name='modelemployee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
