# Generated by Django 3.0.6 on 2020-05-25 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_auto_20200525_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelemployee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='modelemployee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='modelemployee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='modelemployee',
            name='password',
        ),
        migrations.AddField(
            model_name='modelemployee',
            name='slug',
            field=models.CharField(default='onboard', max_length=255),
        ),
        migrations.AddField(
            model_name='modelemployee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelemployee',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identification for an account.', unique=True),
        ),
        migrations.AlterField(
            model_name='modelemployee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ModelPersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')])),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('contact', models.IntegerField()),
                ('post_code', models.IntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.ModelEmployee')),
            ],
            options={
                'verbose_name': 'Personal Details',
                'verbose_name_plural': 'Personal Details',
                'db_table': 'personal_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelFamilyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('siblings', models.IntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.ModelEmployee')),
            ],
            options={
                'verbose_name': 'Family Details',
                'verbose_name_plural': 'Family Details',
                'db_table': 'family_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelEmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_contact', models.IntegerField()),
                ('frient_contact', models.IntegerField()),
                ('gmail', models.EmailField(max_length=50)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.ModelEmployee')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contact',
                'db_table': 'emergency_contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelDocumentGathering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee/documents/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.ModelEmployee')),
            ],
            options={
                'verbose_name': 'Documents',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='ModelBankingInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('ifsc', models.IntegerField()),
                ('acoount_number', models.IntegerField()),
                ('branch_nme', models.CharField(max_length=255)),
                ('bank_address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('bank_post_code', models.IntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.ModelEmployee')),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Detail',
                'db_table': 'bank_detail',
                'managed': True,
            },
        ),
    ]
