# Generated by Django 3.0.6 on 2020-05-26 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0004_auto_20200525_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelBankingInfomation',
            new_name='ModelBankingDetail',
        ),
        migrations.RenameField(
            model_name='modelemergencycontact',
            old_name='gmail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='modelpersonaldetails',
            name='age',
        ),
        migrations.AlterField(
            model_name='modelemployee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
