# Generated by Django 3.0.6 on 2020-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_modelredirecturl_roles_responsibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelemergencycontact',
            old_name='father_contact',
            new_name='contact_1',
        ),
        migrations.RenameField(
            model_name='modelemergencycontact',
            old_name='frient_contact',
            new_name='contact_2',
        ),
        migrations.AddField(
            model_name='modelemergencycontact',
            name='contact_1_relation',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelemergencycontact',
            name='contact_2_relation',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelemergencycontact',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='modelfamilydetails',
            name='siblings',
            field=models.CharField(max_length=255),
        ),
    ]
