# Generated by Django 3.0.6 on 2020-05-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20200527_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpersonaldetails',
            options={'managed': True, 'permissions': (('view_info', 'Can view the personal info'), ('create_profile', 'Can create a profile')), 'verbose_name': 'Personal Details', 'verbose_name_plural': 'Personal Details'},
        ),
    ]
