# Generated by Django 3.0.6 on 2020-05-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20200528_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpersonaldetails',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not specified', 'Not Specified')], max_length=20),
        ),
    ]
