# Generated by Django 3.0.6 on 2020-05-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20200531_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpersonaldetails',
            options={'managed': True, 'verbose_name': 'Personal Details', 'verbose_name_plural': 'Personal Details'},
        ),
    ]
