# Generated by Django 3.0.6 on 2020-06-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20200531_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelredirecturl',
            old_name='bank_detail',
            new_name='ViewBankingInfo',
        ),
        migrations.RenameField(
            model_name='modelredirecturl',
            old_name='document_gathering',
            new_name='ViewDocumentInfo',
        ),
        migrations.RenameField(
            model_name='modelredirecturl',
            old_name='drug_declaration',
            new_name='ViewDrugDeclaration',
        ),
        migrations.RenameField(
            model_name='modelredirecturl',
            old_name='emergency_contact',
            new_name='ViewEmergencyContact',
        ),
        migrations.RenameField(
            model_name='modelredirecturl',
            old_name='family_info',
            new_name='ViewFamilyInfo',
        ),
        migrations.RenameField(
            model_name='modelredirecturl',
            old_name='personal_info',
            new_name='ViewPersonalInfo',
        ),
        migrations.RenameField(
            model_name='modelredirecturl',
            old_name='roles_responsibility',
            new_name='ViewRolesResponsibility',
        ),
    ]
